### ISSUE TITLE
Eliminate the "software agreement" page which appears on startup.

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#10]
It appears on the first run on a device, but not the second.  I don't know if it is using localstorage or something else.

**Comment by KatieWoe** [comment]
If you Exit this dialog (either with the exit button or the x) rather than agree, the sim crashes. Found on Firefox, not limited to that platform. Adding bug tag due to this.
![softwareagreement](https://user-images.githubusercontent.com/41024075/78168467-37ee9180-740d-11ea-8405-541fa8f93fe5.gif)

**Comment by samreid** [comment]
@kathy-phet confirmed to remove this, and I did so in 75122, closing.
