### ISSUE TITLE
When heating molecules, parts of Reversible Reactions freeze

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/decaf#105]
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 10.15.2

<b>Browser</b>

Google Chrome 81.0.4044.122

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/499.

If you heat a molecule for long enough, the scene and some buttons freeze and/or exhibit incorrect behavior. For instance, the reset button no longer resets the scene.

<b>Steps to Reproduce</b>

1. Add a molecule to either chamber.
2. Heat the molecule for a short while. (Happens at about 150000 K for me.)

<b>Visuals</b>

![issue](https://user-images.githubusercontent.com/31285590/80546044-edabf200-8971-11ea-8eb4-7f43e41b6938.gif)

**Comment by oliver-phet** [comment]
We're going to defer on this because it seems to be a narrow case.
