### ISSUE TITLE
Show real glacier image does not come up

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/decaf#109]
For https://github.com/phetsims/QA/issues/499. https://phet-dev.colorado.edu/decaf/glaciers/1.0.0-dev.4/glaciers.html. Similar to https://github.com/phetsims/decaf/issues/32.
When you click the "Show real glaciers" button, the image is blank and see through, leaving just a line and x button to show anything happened.
![showrealglacier](https://user-images.githubusercontent.com/41024075/80623628-b7b94d00-8a07-11ea-9484-dfe5ada33738.gif)

**Comment by samreid** [comment]
Published here: https://phet.colorado.edu/sims/cheerpj/glaciers/latest/glaciers.html
@oliver-phet can you add it to the list?

Afterwards, this issue can be closed.

**Comment by oliver-phet** [comment]
Added.
