### ISSUE TITLE
Publish secondary batch of simulations

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#116]
These notes are duplicated in the spreadsheet and across other issues, from meeting on May 8 with @kathy-phet @oliver-phet @samreid and @KatieWoe.  I indicated I would be able to work on these issues starting Tuesday May 12 at the earliest.

CheerpJ Friday May 8

Capacitor Lab: 1st step, disable the checkbox.  Don't change the text.
But investigate how to get the arrow going on. 15 minutes first.
PClip and PComposite???
Notes in https://github.com/phetsims/decaf/issues/84, report to CheerpJ

Davisson Germer
Won't publish

Fluid Pressure and Flow
Disable Hose
Reach out to CheerpJ, so they can investigate
Short investigation not approved
Disabled checkbox in https://github.com/phetsims/decaf/issues/81, and will report to CheerpJ

Fourier
Disable sound checkbox (leave there), done in https://github.com/phetsims/decaf/issues/85
Reach out to CheerpJ

Glaciers
Remove Show Real Glacier button
units.celsius=\u2103 => C
units.fahrenheit=\u2109 => F
Published here: https://phet.colorado.edu/sims/cheerpj/glaciers/latest/glaciers.html
Tracked in https://github.com/phetsims/decaf/issues/109 and #99 

Greenhouse
Fix unicode K and F, published in #99 

Quantum Wave Interference
Minimum window size fix

Try 
        g2.setRenderingHint( RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_OFF );
        g2.setRenderingHint( RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_SPEED );
        g2.setRenderingHint( RenderingHints.KEY_DITHERING, RenderingHints.VALUE_DITHER_DISABLE );
        g2.setRenderingHint( RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_OFF );
        g2.setRenderingHint( RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR );
        g2.setRenderingHint( RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_SPEED );
        g2.setRenderingHint( RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_DEFAULT );
        g2.setRenderingHint( RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_OFF );

SingleParticleModule. Check the time threshold?
Fixed and deployed to https://phetsims.colorado.edu/sims/cheerpj/quantum-wave-interference/1.0.0-dev.11/quantum-wave-interference.html but stalls during startup
Dev version launches OK: https://phet-dev.colorado.edu/decaf/quantum-wave-interference/1.0.0-dev.11/quantum-wave-interference.html

Sugar and Salt solutions
fix minus sign unicode (all languages)
Under discussion in https://github.com/phetsims/decaf/issues/95

Wait for KP to review the batch of minimum size.
I'll change the ones that say KP votes yes.

**Comment by oliver-phet** [comment]
All these have been published to the public-facing CheerpJ doc, removing my assignment.

**Comment by samreid** [comment]
I reported:

A. In Capacitor Lab: Basics, the Electric Field Detector is supposed to draw text and an arrow, but it comes up blank.  To reproduce this problem:
1. Launch https://phet-dev.colorado.edu/decaf/capacitor-lab/1.0.0-dev.3/capacitor-lab.html?simulation=capacitor-lab
2. Check the "Electric Field Detector" checkbox
3. Observe the empty area in the electric field detector.
It should look more like the version at https://phet.colorado.edu/en/simulation/capacitor-lab
Screenshots are available at https://github.com/phetsims/decaf/issues/84

B. In Fluid Pressure and Flow, moving the hose too high causes a rendering failure
1. Launch https://github.com/phetsims/decaf/issues/81
2. Check the hose checkbox.
3. Start emptying water tower.
4. Move the hose up
Screen capture available at https://github.com/phetsims/decaf/issues/81

C. In Fourier, checking the "sound" checkbox crashes the simulation
1. Launch https://phet-dev.colorado.edu/decaf/fourier/1.0.0-dev.4/fourier.html
2. Check the "Sound" checkbox
The console reports: uncaught exception: out of memory/undefined loader.js:3054:10

D. Quantum Wave Interference works from our development site but not production site:
1. Launching https://phet-dev.colorado.edu/decaf/quantum-wave-interference/1.0.0-dev.11/quantum-wave-interference.html works great
2. Launching https://phetsims.colorado.edu/sims/cheerpj/quantum-wave-interference/1.0.0-dev.11/quantum-wave-interference.html stalls while loading and I cannot figure out why. Any ideas?

**Comment by samreid** [comment]
This batch has been published as far as we can go (https://github.com/phetsims/decaf/issues/118 still needs to be figured out), and we reported problems to CheerpJ, closing.
