### ISSUE TITLE
Remove unintended cheerpj versions from the website

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/decaf#123]
![image](https://user-images.githubusercontent.com/5090275/91777879-430d3f80-ebae-11ea-85c0-440fdecd9bb9.png)

I was just able to reproduce on MacOS Safari 13.1.2 using https://phet.colorado.edu/sims/cheerpj/quantum-wave-interference/latest/quantum-wave-interference.html?simulation=davisson-germer

**Comment by oliver-phet** [comment]
@samreid are you able to investigate?

**Comment by samreid** [comment]
In https://github.com/phetsims/decaf/issues/116#issue-614862244 our consensus was that we wouldn't port Davisson-Germer to CheerpJ.  Does it need to be removed from the sim page or sim database?

**Comment by oliver-phet** [comment]
@samreid yes - I'm not sure why or how it was published, but if we decided not to port it to CheerpJ, it shouldn't be available on the website.

**Comment by samreid** [comment]
Davisson Germer was removed as a "flavor" from the CheerpJ branch in SVN 75157, committed May 14, 2020.  Should we check in with @mattpen about how this can be removed from the website?

**Comment by mattpen** [comment]
I manually set cheerpj to false for davisson-germer in the database. This should be reflected in the website as soon as the cache clears (ETA 15 minutes from the time of this post).

When I was developing the process to add cheerpj sims to the database, I asked @samreid whether we would have a case like this and he said that we would not.  This was likely prior to May 14, but I wasn't aware that this had changed when I added the cheerpj sims to the database.

Adding simulations as a list parameter to [DeployCheerpJ.java](https://github.com/phetsims/website/blob/master/src/java/edu/colorado/phet/website/services/DeployCheerpJ.java) will need to be completed before we deploy another round of CheerpJ sims.

@samreid - do you know of any other cases where there are flavors that were removed from a project for cheerpj? Additionally, is there another round of cheerpj deployments planned soon?  If not, I'll probably defer this work but we should add some kind of reminder to complete the work before the next cheerpj deployment.

**Comment by samreid** [comment]
> Additionally, is there another round of cheerpj deployments planned soon?

Not that I'm aware of.

> Adding simulations as a list parameter to DeployCheerpJ.java will need to be completed before we deploy another round of CheerpJ sims.

Does the metadata come from the simulation build.properties file, or somewhere else?  For instance, the quantum-wave-interference file only declares one "flavor" now.  

> I asked @samreid whether we would have a case like this 

Is the case you are describing "a simulation flavor appears in in Java but not CheerpJ" or another case?

**Comment by mattpen** [comment]
> Is the case you are describing "a simulation flavor appears in in Java but not CheerpJ" or another case?

Yes, that is correct

> Does the metadata come from the simulation build.properties file, or somewhere else? For instance, the quantum-wave-interference file only declares one "flavor" now.

I created an HTTP API for adding these and added a call in the script output that the build script generates.

**Comment by samreid** [comment]
From slack

```
I’m not sure how else I can help with https://github.com/phetsims/decaf/issues/123, let me know if we should have a zoom call

Matt Pennington  10:47 AM
It seems like we don't need to work on the issue now
10:48
But I want to make sure that this issue blocks deployment if we do redeploy at some point in the future.

Sam Reid  10:48 AM
Should we mark the issue as “blocks-publication”?

Matt Pennington  10:49 AM
Will that clutter dev meeting?

Sam Reid  10:49 AM
Probably!  But then everybody would be aware of it.  Maybe mark as “blocks sim publication”?
10:50
Also, what steps would be necessary to make this work with the build process, and how long would it take?  How long does the manual “I manually set cheerpj to false for davisson-germer in the database.” step take?  I’m looking for a break-even point.

Matt Pennington  10:51 AM
The manual step doesn't take long, but it requires that we are aware of the problem.  This page has been sending people to a non-existent cheerpj version of DG since June

Sam Reid  10:52 AM
wow, do we have analytics on that?

Matt Pennington  10:52 AM
We need to add a list of simulations as a query parameter to the deploy api in the cheerpj build script, it probably wouldn't take long but this isn't a high priority for me at the moment

Sam Reid  10:52 AM
Do we need QA to tap through the rest and make sure they don’t have the same problem?
10:52
Me neither!

Matt Pennington  10:54 AM
Were there any other individual flavors removed from projects for the cheerpj deploy? I'm not sure QA is the best answer here, particuarly since they are overworked at the moment

Sam Reid  10:56 AM
I marked it as “blocks sim publication”
10:56
Also removed
10:56
project.flavor.gas-properties.mainclass= edu.colorado.phet.idealgas.GasPropertiesApplication
10:56
project.flavor.sugar-and-salt-solutions-macro.mainclass=edu.colorado.phet.sugarandsaltsolutions.wetlab.SugarAndSaltSolutionsMacroApplication
project.flavor.sugar-and-salt-solutions-micro.mainclass=edu.colorado.phet.sugarandsaltsolutions.wetlab.SugarAndSaltSolutionsMicroApplication
10:57
project.flavor.aphid-maze.mainclass=edu.colorado.phet.ladybugmotion2d.AphidMazeApplication
10:57
project.flavor.under-pressure.mainclass=edu.colorado.phet.underpressure.UnderPressureApplication
10:57
Along with davisson germer, those are all the commits I see.

Matt Pennington  10:58 AM
OK, thanks. I'll investigate

Sam Reid  10:58 AM
Also, I remembered that once we redeployed these to pick up new translations, so next deployment may be scheduled sooner than we expect.

Matt Pennington  10:58 AM
I see
```

**Comment by mattpen** [comment]
These sims have had the cheerpj links removed: davisson-germer, under-pressure

These sims aren't published, so there is no link to fix:  sugar-and-salt-solutions-micro, sugar-and-salt-solutions-macro, aphid-maze

This sim was marked as removed by @samreid, but the cheerpj version is working: gas-properties (see ttps://phet.colorado.edu/sims/cheerpj/ideal-gas/latest/ideal-gas.html?simulation=gas-properties)

Questions: is the gas-properties version correct, or should we remove that link? Should the Sugar/Salt and Aphid Maze sims be published, or were these never public?

**Comment by mattpen** [comment]
@samreid - would you be able to answer those questions or know who can?

**Comment by samreid** [comment]
In https://github.com/phetsims/decaf/issues/115 we decided to remove "gas properties".  Aphid maze was never public.  I don't recall the "micro" and "macro" versions, but they are just simulation subsets (just specific tabs), so they probably don't need to be published.

**Comment by mattpen** [comment]
I removed the database entry for gas properties so that the link is no longer shown, but I don't think this sim was properly removed from the cheerpj version.

**Comment by samreid** [comment]
@mattpen can you please comment what remains to be done for this issue?

**Comment by mattpen** [comment]
1. It looks like ideal gas should be redeployed with gas properties removed.
![image](https://user-images.githubusercontent.com/11747676/94288785-0fa3a380-ff15-11ea-9a19-722d98e093e5.png)

2. I need to update the deployment process to accept a list of simulation names (flavors).  

There may be some confusion about the terms I'm using, it looks like what I call projects and simulations you are calling simulations and flavors.   To clarify by using the gas properties example, I'm referring to ideal gas as the project and gas properties, balloons and buoyancy, and reversible reactions as the simulations.

**Comment by samreid** [comment]
Can the redeploy step be skipped?  The simulation was removed in 75418 so next redeploy it will be removed.  But if gas-properties has been removed from the database, and we don't provide any links to the popup that says "This program contains 3 simulations", could we save time by not redeploying now?  Redeploying will take an hour or so if nothing goes wrong, so that's why I wanted to double check if it is worth the time.

**Comment by mattpen** [comment]
@samreid - it can be discovered if someone launches https://phet.colorado.edu/sims/cheerpj/ideal-gas/latest/ideal-gas.html. If this is acceptable we can defer a redeploy.

**Comment by samreid** [comment]
I think the odds of someone launching that URL with no query parameters are low (could maybe be checked with analytics?), hence I'm inclined to hold off on the redeploy.  But this is just a recommendation and not a decision, I'm happy to defer if others feel strongly.

**Comment by mattpen** [comment]
That's ok with me.  Let's resume this issue when we redeploy for translation updates.

**Comment by mattpen** [comment]
@samreid - we should be ready to proceed with the next round of cheerpj deploys on Monday.

**Comment by samreid** [comment]
From https://github.com/phetsims/decaf/issues/124#issuecomment-703766499

> Working together, @mattpen and I deployed quantum-wave-interference and confirmed that the davisson-germer simulation was not affected.

I also committed a fix that changes the service URL.

**Comment by mattpen** [comment]
The latest round of deploys worked nicely and did not readd any problematic links. Closing.
