### ISSUE TITLE
Build and deploy steps for cheerpj sims only work on macOS

### ISSUE THREAD

**Issue by Denz1994** [phetsims/decaf#127]
During @samreid and I concluded that the steps to build and deploy cheerpj sims only works on macOS. There are specific paths for the JDK that follow conventions on macOS. This issue is created to determine if we wanted to spend resources making the build and deploy steps cross-platform, like all of our other build and deploy tools. We estimate this could take between 5-20 hours.

Assigning to @ariel-phet to add input.

**Comment by ariel-phet** [comment]
@Denz1994 @samreid - I do not think that is necessary at this point. As long as the documentation is clear that the steps can on be performed on macOS that is fine since multiple developers have access to that platform.
