### ISSUE TITLE
Investigate CheerpJ 2.2 to see if it has better performance or smaller download

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#130]
CheerpJ 2.2 was released today.  We would like to investigate CheerpJ 2.2 to see if it has better performance or smaller download.

**Comment by samreid** [comment]
@kathy-phet said:

> We have higher priorities right now, but might want to look into this later in the summer to see if it is faster.

**Comment by samreid** [comment]
I ran a local build of battery-resistor circuit using cheerpj 2.1 and 2.2 and observed the following:

2.1 BRC
time to sim display: 12.15sec, 10.59sec, 9.04sec, 9.08sec
25.1MB
262 requests
102MB resources

2.2 BRC
time to sim display: 9.04sec, 9.4sec, 9.1sec, 9.06sec
25.3MB
264 requests
104MB resources

I attribute the longer startup times for the first runs of 2.1 due to a "warm up" period.  I don't see a significant difference between these numbers.

Reading into the 2.2 change log, I see:
https://leaningtech.com/cheerpj-2-2-released/

* Optimized exception handling
* Extended JNI support
* Improved file system emulation
* Improved HTTP networking support
* Improved AWT support
* Improved audio support
* Improved reflection support
* Improved applet parsing robustness
* Improved correctness of 32-bit floating point
* Improved correctness of class private methods

None of these looks like a performance boost for our circumstances.

I also observed the following during this investigation:
* We are still using a custom-built loader instead of the public loader https://cjrt.leaningtech.com/2.1/loader.js.  Since we have tested against the custom-built one, and it seems stable, it doesn't seem worth it to transition at this time
* There are some minor layout adjustments between 2.1 and 2.2, mainly from text sizing.  When we eventually upgrade to 2.3 or higher, we will need a full QA cycle.

Therefore, I recommend closing this issue.  I will make a calendar reminder to notify @kathy-phet over slack.

**Comment by kathy-phet** [comment]
Thanks for taking a look, Sam! Agreed ... let's not upgrade.
