### ISSUE TITLE
General Performance Issues

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/decaf#21]
For https://phet-dev.colorado.edu/decaf/conductivity/1.0.0-dev.2/. Linking to https://github.com/phetsims/QA/issues/489.

**Original Issue**
On Chromebook. There is minor lag in Conductivity, but it doesn't seem to impact it terribly. Mostly seen in the photons from the flashlight and the electrons in the close up of the material.

**Comment by KatieWoe** [comment]
Making this an issue for general performance issues. Most sims I have encountered have this minor, but noticeable lag. It doesn't impact pedagogy or use, but sliders take time to react, buttons may take a second to register, and animations are slower.

**Comment by lmulhall-phet** [comment]
In Band Structure, if you mouse over the energy levels, the clock slows down significantly:

![issue](https://user-images.githubusercontent.com/31285590/78301520-6bf1b180-74f6-11ea-9112-b578eb44e698.gif)

**Comment by KatieWoe** [comment]
Alpha decay and other instance of large numbers or shaking/decaying atoms causes a noticeable slow down that doesn't impact learning, but is fairly large.

**Comment by samreid** [comment]
On Slack, @kathy-phet indicated it would be nice to profile sims such as Reactions and Rates, and report to CheerpJ to see if they have an opportunity for optimization. 

I noted that Reactions and Rates is spending 30% of its time in something called `_Java_sun_java2d_loops_TransformHelper_Transform.`

**Comment by samreid** [comment]
@kathy-phet recommended to profile some of the more popular java sims.  Leaving self-assigned to do so.  For timing, @kathy-phet said:

> (Not immediately necessarily, but as something they can use to help them optimize performance of their code)

**Comment by samreid** [comment]
On slack, I asked 

> I’m trying to decide which CheerpJ sims to check performance on for https://github.com/phetsims/decaf/issues/21.  Can you help me choose? 

and @KatieWoe said:

> [...] hydrogen atom, conductivity, and maybe natural selection seem stable and useful. Some performance slow down, but overall useful.

**Comment by samreid** [comment]
https://phet-dev.colorado.edu/decaf/hydrogen-atom/1.0.0-dev.4/hydrogen-atom.html looks like 60% is being spent in RepaintManager.doublebuffered (with the "on" button pressed)

![image](https://user-images.githubusercontent.com/679486/80509302-77d66500-8936-11ea-96b3-54e39555de0d.png)

With 15% spent in `putImageData`

![image](https://user-images.githubusercontent.com/679486/80509414-9e949b80-8936-11ea-803a-e1f141e26cdb.png)

**Comment by samreid** [comment]
In https://phet-dev.colorado.edu/decaf/hydrogen-atom/1.0.0-dev.4/hydrogen-atom.html on Mac/Chrome after pressing the "on" button, looks like 60% is being spent as a result of RepaintManager.doublebuffered.

In https://phet-dev.colorado.edu/decaf/conductivity/1.0.0-dev.4/conductivity.html, turning the voltage up to 2.0 Mac/Chrome shows 50% time spent in _Java_sun_java2d_loops_ScaledBlit_Scale, and around 40% time spent in ApparatusPanel.paint.

https://phet-dev.colorado.edu/decaf/natural-selection/1.0.0-dev.4/natural-selection.html then clicking "add a friend" on Mac/Chrome shows 66% as a result of RepaintManager.doubleBuffered.

I'll reach out to CheerpJ.

**Comment by samreid** [comment]
@kathy-phet said:

> Thanks, Sam. My inclination is that for now, we just live with a performance degradation. Bringing sims to html is where we should focus our time, so if they don't think they can do anything or if it will cost them resources, I'm not particularly interested in pursuing it.
