### ISSUE TITLE
Add analytics to the HTML wrapper

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#27]
@jonathanolson indicated it would be nice to send explicit analytics messages from the HTML.  @jonathanolson can you please describe what this would look like, or take the lead on it?  The launch files are in html/

**Comment by jonathanolson** [comment]
Should be good to go, just fill out:
```js
  // TODO: fill these in with values!
  var project = 'placeholder-project';
  var sim = 'placeholder-sim';
  var version = '1.0.0-dev.0';
  var locale = 'en';
```
with the values used.

**Comment by samreid** [comment]
@jonathanolson also mentioned the in-Java analytics have been down for a while, and that we should disable the Java-side analytics (for CheerpJ sims only) before proceeding with this code.

**Comment by samreid** [comment]
Decaf "in-java" analytics removed in https://phet.unfuddle.com/a#/repositories/23262/commit?commit=75122

**Comment by samreid** [comment]
I published https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.3/index.html?simulation=faraday with the analytics.  It should have sent a few messages by now.  @jonathanolson can you please take a look and see if it is working as expected?  Or/additionally look at the JS in that HTML link to make sure it looks reasonable.

**Comment by jonathanolson** [comment]
Looks good to me!
