### ISSUE TITLE
Can we make the sims "fullscreen" so that they don't take up a subspace of the browser area?

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#28]
Can we make the sims "fullscreen" so that they don't take up a subspace of the browser area?

**Comment by samreid** [comment]
I tried:

```diff
Index: simulations-java/common/phetcommon/src/edu/colorado/phet/common/phetcommon/view/util/FrameSetup.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- simulations-java/common/phetcommon/src/edu/colorado/phet/common/phetcommon/view/util/FrameSetup.java	(revision 75120)
+++ simulations-java/common/phetcommon/src/edu/colorado/phet/common/phetcommon/view/util/FrameSetup.java	(date 1585887877328)
@@ -87,6 +87,9 @@
             frame.setLocation( (int) getAvailableRectangle().getCenterX() - frameWidth / 2,
                                (int) getAvailableRectangle().getCenterY() - frameHeight / 2 );
             frame.setSize( frameWidth, frameHeight );
+
+            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
+            frame.setUndecorated(true);
         }
 
         //Returns true if the requested window size would not fit on the actual main screen, accounting for the size of toolbars and other insets.

```

And it had the same behavior as before.  Perhaps CheerpJ doesn't yet support fullscreen?

**Comment by samreid** [comment]
CheerpJ reported:

> CheerpJ windows do nor currently support a Maximized status, as you can see the maximize button is also not offered on the window title bars.
> 
> Supporting maximization would be a fully new feature, not something than can be quickly fixed. The work around I can suggest is to convert the application to an applet. Java applets running in CheerpJ are automatically resized to the size of their <object>/<cheerpj-object> element.

**Comment by samreid** [comment]
I added code to get the startup innerWidth x innerHeight and send a notification when that changes.  It works OK on my Chrome and mobile safari, but on my mobile safari, sometimes the top is cut off when the address bar is too big.  But I found out that you can shrink the address bar by swiping it up.  I published a version here:

https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.15/index.html?simulation=faraday

@KatieWoe can you please test out the window sizing behavior (initial size and when browser resizes or device rotates) in this version?  Would be good to briefly test on several devices and browsers.

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] Win 10 IE
- [ ] Mac 10.15 Safari
- [ ] Mac 10.15 Chrome
- [ ] iPhone Safari
- [ ] iPad 13 Safari
- [ ] ChromeOS

@samreid does this list look ok?

**Comment by samreid** [comment]
Does Mac firefox mostly behave like Win firefox?  Other than that, everything sounds great!

**Comment by KatieWoe** [comment]
We don't support it anymore, but I can add it if you want

**Comment by samreid** [comment]
I didn't know that--if we don't support it, no need to test on that. Thanks for getting me up to speed!

**Comment by samreid** [comment]
@kathy-phet said on Windows Chrome it always creates scrollbars regardless of the window size:

![image](https://user-images.githubusercontent.com/679486/79010283-e89c1580-7b1e-11ea-8961-5f1e5c96664e.png)

**Comment by samreid** [comment]
This version removes the scrollbars on my Win/Chrome: https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.16/index.html?simulation=faraday

This change will require re-testing across platforms.

**Comment by KatieWoe** [comment]
Noting that in IE there is a significant lag in attempts to resize the window, with the window sometimes failing to even respond.

**Comment by samreid** [comment]
I also noticed that delay in Mac Safari.

**Comment by KatieWoe** [comment]
I believe QA is done with this round of window resizing testing.

**Comment by samreid** [comment]
Thanks!  Closing.
