### ISSUE TITLE
Lasers fails to load

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/decaf#29]
For https://github.com/phetsims/QA/issues/489
https://phet-dev.colorado.edu/decaf/lasers/1.0.0-dev.2/

Lasers fails to load on Windows 10 IE & Chrome.

Error does appear in the console for Windows 10 IE are as follows:

```
HTML1506: Unexpected token.
1.0.0-dev.2 (26,1)
CheerpJ is initializing
Reporting error: Script error.
SCRIPT5009: '_c4pbM_8nG1uocdGbrnTidabrkDjsqD9ueqJuHteZMONn' is undefined
loader.js (401,4)
SEC7120: Origin https://phet-dev.colorado.edu not found in Access-Control-Allow-Origin header.
1.0.0-dev.2
SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, Could not complete the operation due to error 80700013.
1.0.0-dev.2
```

![2020-04-02DecafLasers](https://user-images.githubusercontent.com/54685448/78299347-e4567380-74f2-11ea-993f-52badcdbacc2.gif)

**Comment by samreid** [comment]
Caused by #9, we'll track it there
