### ISSUE TITLE
Nuclear Fission Show Reactor button does not bring up image and may not be exitable

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/decaf#32]
For https://phet-dev.colorado.edu/decaf/nuclear-physics/1.0.0-dev.2/
Found on ChromeOS, Win 10 Chrome, Firefox, etc. Found in Nuclear Fission sim on Nuclear Reactor screen. If you push the "Picture of a Reactor" button, it should show an image of a reactor. Instead, only an outline shows up. Nothing is intractable at this point aside from the x to leave the image that isn't there. In Chrome on Windows it is so faint I almost missed it, which could leave the sim unusable to a user.
![nopicture](https://user-images.githubusercontent.com/41024075/78304500-220bca00-74fc-11ea-88fe-c6a56d26d481.png)
![onfirefox](https://user-images.githubusercontent.com/41024075/78304503-233cf700-74fc-11ea-83b2-e9c05ad38d78.png)

**Comment by KatieWoe** [comment]
Still occurs in https://github.com/phetsims/QA/issues/499

**Comment by kathy-phet** [comment]
@samreid - Can you look into this bug and whether it is something that should be reported to CheerpJ?

**Comment by oliver-phet** [comment]
@samreid will remove button to image, then publish.

**Comment by samreid** [comment]
Committed in 75139

**Comment by samreid** [comment]
Published in https://phet.colorado.edu/sims/cheerpj/nuclear-physics/latest/nuclear-physics.html?simulation=nuclear-fission

Reassigning to @KatieWoe and @oliver-phet for next steps, if any.

**Comment by KatieWoe** [comment]
Confirmed that the button is gone in Win 10 chrome

**Comment by samreid** [comment]
Published, closing.
