### ISSUE TITLE
Quantum Wave Interference play area colored light color

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/decaf#35]
For https://phet-dev.colorado.edu/decaf/quantum-wave-interference/1.0.0-dev.2/. Seen in ChromeOS and Win 10 Chrome. Quantum Wave Interference Sim.  On the second screen the background to the play area turns the color of the default light after a second or two. It reverts to normal if you send a photon, then returns to the bugged behavior. Not in published version. I also noticed that the sim is particularly slow in ChromeOS, To the point that it may be difficult to use. Specifically as light moves from the source to the screen.
Published:
![shouldbe](https://user-images.githubusercontent.com/41024075/78411504-1e944380-75cd-11ea-9c06-5e866ce3c8ce.png)
CheerpJ version:
![islikethis](https://user-images.githubusercontent.com/41024075/78411510-2522bb00-75cd-11ea-8dfe-d63eea8a6fad.png)
![movingpicture](https://user-images.githubusercontent.com/41024075/78411512-25bb5180-75cd-11ea-9ada-a30bc77709bf.gif)

**Comment by KatieWoe** [comment]
Still occurs in https://github.com/phetsims/QA/issues/499

**Comment by samreid** [comment]
I fixed this by avoiding a divide by zero error.  But after deploying, the startup sequence is hanging.  But it works on my localhost.  I'm not sure where the problem lies.

**Comment by samreid** [comment]
I published a production version here:

https://phet.colorado.edu/sims/cheerpj/quantum-wave-interference/1.0.0-dev.12/quantum-wave-interference.html

@KatieWoe can you test this and https://github.com/phetsims/decaf/issues/103 ?

If all is well, give Oliver the go-ahead to publish with URL:

https://phet.colorado.edu/sims/cheerpj/quantum-wave-interference/latest/quantum-wave-interference.html

**Comment by KatieWoe** [comment]
Looks good. Tested on a few platforms. @oliver-phet

**Comment by oliver-phet** [comment]
Ok I just updated the links to that sim. Closing!
