### ISSUE TITLE
Select a simulation for initial publication

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#37]
It would be nice to choose a simulation to move forward for initial publication.  @KatieWoe may have a good recommendation based on her testing.  From my perspective, Hydrogen Atom seemed like a reasonable starting point, but I'd like to hear from @KatieWoe and @kathy-phet about their recommendations.

On slack last Wednesday, I asked @KatieWoe what she thought, and she said:

> Simpler ones that don't have quite as much user input, so the lag interferes less. Such as Microwave, Hydrogen Atom, Battery Resistor Circuit, etc.

There has been more testing since then and she may have more to add.

**Comment by loganbraywork** [comment]
Ladybug-motion-2D worked the best out of all of the decaf sims I tested

**Comment by KatieWoe** [comment]
When a sim is decided for this issue, we should do more in depth testing on it before it goes out, since this last round only did one platform per sim. Maybe we should pick more than one and see which works better between the different platforms.

**Comment by kathy-phet** [comment]
I would like to pick something that would be being used soon. I just played with Faraday's Electromagnetic Lab on my computer, and it seemed pretty good. How did that work for you? 
@samreid - Can that be generated so that it doesn't require the "offline acceptance" ask, and also starts without the dialog to ask which sim to run?

**Comment by samreid** [comment]
@kathy-phet by the "offline acceptance" ask, do you mean this dialog?

![image](https://user-images.githubusercontent.com/679486/78599454-6524b080-780e-11ea-952d-9df4418bb97a.png)

**Comment by samreid** [comment]
I removed that in svn revision 75122

**Comment by samreid** [comment]
This version removes the offline acceptance ask, removes the simulation selector, and supports ?locale query parameter.  Note the simulation is specified in the query parameter too:
https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.3/index.html?simulation=faraday

For instance:
https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.3/index.html?simulation=faraday&locale=fr

**Comment by ariel-phet** [comment]
I concur that Faraday's Electromagnetic lab would be a great sim to publish, as it would be very popular.

As a data point, the first link above runs beautifully on Chrome, but is quite laggy on Firefox.

**Comment by samreid** [comment]
We have selected Faraday and will move forward in other issues, closing.
