### ISSUE TITLE
Make a GIF for the start up splash screen

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/decaf#39]
We will need to make a GIF that has a moving circle or line or something, but that rebrands the splash screen with something like this. Sam has figured out a work around to make this change.  
![image](https://user-images.githubusercontent.com/5096804/78599403-4aead280-780e-11ea-9541-968ca8c898f7.png)

Can someone make a splash screen gif?

**Comment by amanda-phet** [comment]
(1) **Will the animation be done in code by @samreid or do you want a GIF?** Are you sure it's a GIF that we want for this? I assumed that loading animation was done in code. 
(2) **Are there requirements for the animation (from cheerpj)?** Do you recall if cheerpj wants a loading circle around their logo, or if we can do something different? I think since we are making a wider splash screen design, we might want something more horizontal under the entire image. 
(3) **Should the text be an image, or should it be in code?** I can mock up an idea for this, but it seems like we shouldn't use an image in the end, and rather this should be done in code using images for logos.

**Comment by kathy-phet** [comment]
I like it too!

**Comment by kathy-phet** [comment]
I think you could make a gif by making it animate like this in your powerpoint or something like that and then taking a sort movie of that using camtasia.

**Comment by samreid** [comment]
Powerpoint can also export GIFs directly.  You can also create gifs in Illustrator and Photoshop.

**Comment by amanda-phet** [comment]
@samreid Can I just give you two image assets, one that says "PhET Java Simulations" and another that says "Powered By cheerpj" and you can sandwich them around this gif I made?

**Comment by samreid** [comment]
I'm not sure how I'll do it (maybe using Photoshop), but send them along and I'll try some ideas, thanks!

**Comment by amanda-phet** [comment]
I meant just arrange them on the splash screen. If that's not possible I will make a single gif for you.

**Comment by kathy-phet** [comment]
Amanda - I am sure it will need to be a single gif. We are basically overriding what they have so it needs to be a single file name.

**Comment by amanda-phet** [comment]
![loading](https://user-images.githubusercontent.com/7852916/78709646-391e3380-78d1-11ea-8947-36a4319be5f1.gif)

Please give me your polishes! I got it working, so I can adjust sizes of logos, overall size of gif, etc.

**Comment by samreid** [comment]
To clarify, the proposed strategy works by putting the new logo in front of the existing logo (not by replacing it).  It could be done with arbitrary HTML, but a single gif will be simpler.

* The "powered by" text is too close in size to the "cheerpj" text.  What do you think about using the cheerpj text to the side like in this one--makes it a bit bigger and matches its size more closely to the PhET logo? https://github.com/phetsims/decaf/issues/39#issuecomment-610011915

**Comment by samreid** [comment]
To experiment with the code for this part, I opened #41 and used the gif from 2 comments back.  The result is here, in case you want to see that logo gif in context: https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.5/?simulation=faraday

**Comment by amanda-phet** [comment]
![java-cheerpj-loading](https://user-images.githubusercontent.com/7852916/78799424-57d70580-7977-11ea-92c0-48fd5e5bb0c2.gif)

**Comment by kathy-phet** [comment]
I actually have a slight preference for the prior version, but can go either way.

**Comment by amanda-phet** [comment]
This has been in production for a while, so this can be closed!
