### ISSUE TITLE
Add a custom splash screen

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#41]
In https://github.com/phetsims/decaf/issues/39 the splash screen is being designed.  @kathy-phet discussed with CheerpJ about the business side.  This issue is for technical aspects for how to add the splash screen to the launch.  

I tried adding this code to our HTML body:

```html
<link rel="stylesheet" type="text/css" href="css.css">
```
Then in the stylesheet, I replaced the splash image:

```css
.cheerpjLoading:before {
  background-image: url("http://localhost/main/brand/phet/images/logo-on-white.png");
}
```

The result was that it showed the PhET logo during startup.  

![image](https://user-images.githubusercontent.com/679486/78714211-b4371800-78d8-11ea-85f3-142fc6e3d12a.png)

Of course we could add any image or animation here.  I only tested this on Chrome, but it seems like a strategy like this may work well for our purposes if CheerpJ does not provide an explicit way to accomplish this.  @jonathanolson and @chrisklus would have good expertise on this strategy if we want to pursue it.

One downside of this strategy is it relies on internal variable names and sequencing in the CheerpJ, so if they re-uploaded CheerpJ 2.1 with a different variable name or loading strategy, then it would revert back to their original logo.  There could be ways to overcome this, say, by putting a new splash screen with an opaque background in front of everything.  Again @jonathanolson and @chrisklus  would know best how to do this.

I'll commit the proposal above so it can be tested on more platforms and/or discussed further.

**Comment by samreid** [comment]
I added this strategy and published a sample version here: https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.5/?simulation=faraday

This tested OK on my mac chrome/firefox/safari.

@KatieWoe can you please test across a few more platforms, like chromebook and ipad?

**Comment by KatieWoe** [comment]
IE gives an error. Not sure if it is related to the splash screen:
![ieerror](https://user-images.githubusercontent.com/41024075/78724087-e69d4100-78e9-11ea-853d-ef570ebb72c6.png)

**Comment by samreid** [comment]
Maybe it was caused by let/const.  I converted them to var in this version, can you please take a look?https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.6/index.html

**Comment by KatieWoe** [comment]
Still happens there

**Comment by KatieWoe** [comment]
Checked a few other platforms, and they looked ok

**Comment by kathy-phet** [comment]
Sam - On IE, splash screen works in dev.2 but not in dev.3. I believe dev.3 was probably before you added the custom splash screen. dev.2 has an error but still launches in the end.

**Comment by samreid** [comment]
I fixed the HTML IE errors, but I saw the error dialog I think @kathy-phet was referring to.  That still needs investigation.

**Comment by samreid** [comment]
I should also mention that neither splash screen shows on IE.

**Comment by samreid** [comment]
I repaired this startup failure and deployed here: https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.7/index.html?simulation=faraday

It's launching OK on my IE.

**Comment by samreid** [comment]
@KatieWoe can you please confirm on your IE setup?  If it's OK, please close.

**Comment by KatieWoe** [comment]
Loads up and the splash screen looks ok on IE for me
