### ISSUE TITLE
Make it possible to launch a single sim from a multi-sim JAR

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#5]
For example, I converted the "Faraday" "all" jar, and it shows this dialog on startup:

![image](https://user-images.githubusercontent.com/679486/78073666-8db83080-735e-11ea-8ae7-932c0340cc77.png)

This will be sufficient for testing, but eventually we will need to know how to launch a single simulation from a multi-sim jar file.  That will be simpler and more streamlined than converting one jar per simulation.

In https://github.com/phetsims/cheerpj/issues/2#issuecomment-606837121 @pixelzoom said we can put the JAR on the classpath and specify main instead.

**Comment by samreid** [comment]
I tried:

```
cd decaf/projects/faraday
java -cp faraday_all.jar edu.colorado.phet.faraday.FaradayApplication
```

And it correctly launched the "Faraday's Electromagnetic Lab" simulation from this Jar file.  However, when I converted:

```js
cheerpjRunJar( "/app/main/decaf/projects/faraday/faraday_all.jar" );
```

to 
```js
cheerpjRunMain("edu.colorado.phet.faraday.FaradayApplication", "/app/main/decaf/projects/faraday/faraday_all.jar");
```

Startup failed with this error:

![image](https://user-images.githubusercontent.com/679486/78090614-d6381400-7387-11ea-96cc-8a6b36090ab8.png)

and 

![image](https://user-images.githubusercontent.com/679486/78090629-e2bc6c80-7387-11ea-9d20-8ca01ed9f691.png)

I also noted a typo in the documentation at https://github.com/leaningtech/cheerpj-meta/wiki/Runtime-API where in once case "cheerpjRunMain" is written instead as "cherpjRunMain".

**Comment by samreid** [comment]
In https://github.com/phetsims/decaf/commit/ddfd29f129c8819f82bffbbb9bc06f7305a5979b I added a html file that specifies this main.  To test it, please update it to point to the correct local path after "app" (note my path has "main").

**Comment by samreid** [comment]
I also tried stripping out the MANIFEST directory, and had the same problem.

**Comment by samreid** [comment]
I got the PBG working by the following steps:

1. Fresh checkout of SVN
2. Create IDEA project using the .idea folder that came with the checkout
3. Upgrade lombok and and proguard to latest versions
lombok to 1.18.12
proguard to 6.2.2

Replace these jars:

![image](https://user-images.githubusercontent.com/679486/78208248-2931ca00-7461-11ea-9728-1a0c7fc984e5.png)

Then I added this patch:

```diff
Index: simulations-java/common/phetcommon/src/edu/colorado/phet/common/phetcommon/application/JARLauncher.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- simulations-java/common/phetcommon/src/edu/colorado/phet/common/phetcommon/application/JARLauncher.java	(revision 75119)
+++ simulations-java/common/phetcommon/src/edu/colorado/phet/common/phetcommon/application/JARLauncher.java	(date 1585798506024)
@@ -85,7 +85,7 @@
 
     public JARLauncher( String[] args ) throws IOException, ClassNotFoundException, NoSuchMethodException, IllegalAccessException, InvocationTargetException {
 
-        // Read properties 
+        // Read properties
         Properties properties = readProperties( PROPERTIES_FILE_NAME );
 
         // Determine which sims are in this JAR
@@ -99,6 +99,11 @@
 
         // Launch a sim
         String mainFlavor = properties.getProperty( FLAVOR_KEY );
+
+        if (args.length>=2 && args[0].equals("flavor")){
+            mainFlavor = args[1];
+        }
+
         if ( mainFlavor != null ) {
             // properties file specifies which sim to launch
             SimulationInfo sim = getFlavor( sims, mainFlavor );
```

And CheerpJ can launch different flavors via:

```js
cheerpjRunJar( "/app/main/decaf/projects/faraday/faraday_all.jar","flavor","generator" );
```

I still need to work out where to put this code, probably an SVN branch.

**Comment by samreid** [comment]
I committed the changes to an SVN branch.

**Comment by samreid** [comment]
I added support for the null flavor in https://phet.unfuddle.com/a#/repositories/23262/commit?commit=75124

**Comment by samreid** [comment]
Simulations can now be launched with a ?simulation query parameter, where the values are identified in the jar-launcher.properties file in the JAR.   Closing.

**Comment by pixelzoom** [comment]
Reopening... For posterity, can you please explain what "the null flavor" is?

**Comment by samreid** [comment]
To simplify the code, cheerpJ launch is always called with a "flavor", and if the flavor is "null", this maps back to null on the Java side like in JARLauncher

```java
// Allow specifying the flavor via command line arguments
if (args.length >= 2 && args[0].equals("flavor")) {
    mainFlavor = args[1];
    if (mainFlavor.equals("null")) {
        mainFlavor = null;
    }
}
```

That will trigger showing the flavor-selector dialog for projects with more than one flavor.
