### ISSUE TITLE
Faraday performance

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#65]
The performance of Faraday has been reported as suboptimal in #56 #63 and general performance problems have been noted in #21.  

In https://github.com/phetsims/QA/issues/494#issuecomment-613623340 @ariel-phet said:

> @samreid - it looks like you have made a change where the sim opens at the browser window size, although that is nice in theory it absolutely TANKS performance for me.

Reducing the paint area is one way to improve performance, but may not be the best way.  We will discuss it at a meeting later today.

Brainstorming ways to improve performance:
* Reach out to CheerpJ to identify this performance issue and see if they can improve this part of the code
* Come up with a heuristic for reducing the window size.  But do this without allowing the window to be cut off in either direction and make it robust against tablet rotation, window resize, etc.
* Reduce the grid resolution
* Change the Java code to improve the performance.  Perhaps render images instead of drawing shapes.  The original code by @pixelzoom caches up to 360 shapes then paints them with different opacities. 
* Add a note "If you are experiencing performance problems", try a smaller window

```java
// Draw the needles.
double previousX, previousY;
previousX = previousY = 0;
for ( int i = 0; i < _gridPoints.length; i++ ) {

    GridPoint gridPoint = _gridPoints[i];

    northColor = _needleCache.getNorthColor( gridPoint.getIntensity() );
    southColor = _needleCache.getSouthColor( gridPoint.getIntensity() );
    northShape = _needleCache.getNorthShape( gridPoint.getDirection() );
    southShape = _needleCache.getSouthShape( gridPoint.getDirection() );

    if ( gridPoint.getIntensity() >= _strengthThreshold ) {

        g2.translate( gridPoint.getX() - previousX, gridPoint.getY() - previousY );
        g2.setPaint( northColor );
        g2.fill( northShape );
        g2.setPaint( southColor );
        g2.fill( southShape );

        previousX = gridPoint.getX();
        previousY = gridPoint.getY();
    }
}
```

**Comment by samreid** [comment]
70% of the application time is being spent in AbstractFieldGraphic.paint:

![image](https://user-images.githubusercontent.com/679486/79482618-4ffa0f80-7fce-11ea-9a8e-9166efadd521.png)

**Comment by pixelzoom** [comment]
> Change the Java code to improve the performance. Perhaps render images instead of drawing shapes. The original code by @pixelzoom caches up to 360 shapes then paints them with different opacities.

I recall that performance optimization was a huge part of getting this working (back in 2005?)
I dimly remember trying different approaches and discovering that performance was better with shapes + opacity than with images + opacity.  But I may be mistaken, or optimizations may have changed in the JRE since them.

**Comment by pixelzoom** [comment]
If you proceed with changes to the Java version, it's highly recommended to look through the commit history to identify optimizations, so that regressions are not introduced. 

Some things to be aware of:

* If using images, beware that you'll need to support the options under "Options > Field Controls", including the needle size and spacing.

* AbstractFieldGraphic optimizes rendering on the (default) black background, see SVN version 2076.   "Options > Background Color" allows you to change the background color (sort of an early version of Projector Mode) but with a performance penalty.

* There's a performance optimization called FastGridNeedle, introduced in SVN version 2117.

Also wondering... Are you generally making sim changes needed by Cheerpj in a branch or in trunk. I'm hoping in trunk, so that I don't potentially encounter problems when porting to HTML5.

**Comment by samreid** [comment]
Here's a feasibility patch that uses images:

<details>

```diff
Index: simulations-java/simulations/faraday/src/edu/colorado/phet/faraday/view/AbstractBFieldGraphic.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- simulations-java/simulations/faraday/src/edu/colorado/phet/faraday/view/AbstractBFieldGraphic.java	(revision 75120)
+++ simulations-java/simulations/faraday/src/edu/colorado/phet/faraday/view/AbstractBFieldGraphic.java	(date 1587056594344)
@@ -2,19 +2,15 @@
 
 package edu.colorado.phet.faraday.view;
 
-import java.awt.Color;
-import java.awt.Component;
-import java.awt.Dimension;
-import java.awt.Graphics2D;
-import java.awt.Point;
-import java.awt.Rectangle;
-import java.awt.RenderingHints;
-import java.awt.Shape;
+import java.awt.*;
+import java.awt.geom.AffineTransform;
+import java.awt.image.BufferedImage;
 
 import edu.colorado.phet.common.phetcommon.math.vector.MutableVector2D;
 import edu.colorado.phet.common.phetcommon.simsharing.components.NonInteractiveEventListener;
 import edu.colorado.phet.common.phetgraphics.view.phetgraphics.PhetGraphic;
 import edu.colorado.phet.faraday.FaradayConstants;
+import edu.colorado.phet.faraday.FaradayResources;
 import edu.colorado.phet.faraday.FaradaySimSharing.Components;
 import edu.colorado.phet.faraday.model.AbstractMagnet;
 
@@ -68,6 +64,7 @@
     // Scaling of the intensity, see setIntensityScale
     private double _intensityScale;
 
+    BufferedImage resistorImage = FaradayResources.getImage( FaradayConstants.NEEDLE_IMAGE );
 
     //----------------------------------------------------------------------------
     // Inner classes
@@ -344,18 +341,23 @@
 
                 GridPoint gridPoint = _gridPoints[i];
 
-                northColor = _needleCache.getNorthColor( gridPoint.getIntensity() );
-                southColor = _needleCache.getSouthColor( gridPoint.getIntensity() );
-                northShape = _needleCache.getNorthShape( gridPoint.getDirection() );
-                southShape = _needleCache.getSouthShape( gridPoint.getDirection() );
+//                northColor = _needleCache.getNorthColor( gridPoint.getIntensity() );
+//                southColor = _needleCache.getSouthColor( gridPoint.getIntensity() );
+//                northShape = _needleCache.getNorthShape( gridPoint.getDirection() );
+//                southShape = _needleCache.getSouthShape( gridPoint.getDirection() );
 
                 if ( gridPoint.getIntensity() >= _strengthThreshold ) {
 
                     g2.translate( gridPoint.getX() - previousX, gridPoint.getY() - previousY );
-                    g2.setPaint( northColor );
-                    g2.fill( northShape );
-                    g2.setPaint( southColor );
-                    g2.fill( southShape );
+
+                    g2.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER,(float) gridPoint.getIntensity()));
+//                    g2.drawImage(resistorImage, null,0,0);
+
+                    g2.drawImage(resistorImage, AffineTransform.getRotateInstance(gridPoint.getDirection()), null);
+//                    g2.setPaint( northColor );
+//                    g2.fill( northShape );
+//                    g2.setPaint( southColor );
+//                    g2.fill( southShape );
 
                     previousX = gridPoint.getX();
                     previousY = gridPoint.getY();
Index: simulations-java/simulations/faraday/src/edu/colorado/phet/faraday/FaradayConstants.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- simulations-java/simulations/faraday/src/edu/colorado/phet/faraday/FaradayConstants.java	(revision 75120)
+++ simulations-java/simulations/faraday/src/edu/colorado/phet/faraday/FaradayConstants.java	(date 1587056503707)
@@ -68,6 +68,7 @@
     public static final String LIGHTBULB_ICON = "lightbulb_icon.png";
     public static final String LIGHTBULB_ICON_SELECTED = "lightbulb_icon_selected.png";
     public static final String RESISTOR_IMAGE = "resistor.png";
+    public static final String NEEDLE_IMAGE = "needle.png";
     public static final String SLIDER_KNOB_IMAGE = "sliderKnob.png";
     public static final String SLIDER_KNOB_HIGHLIGHT_IMAGE = "sliderKnobHighlight.png";
     public static final String TURBINE_PIVOT_IMAGE = "turbinePivot.png";

```


</details>

**Comment by samreid** [comment]
This version uses images instead of shapes (dimensions and transforms are not fine tuned, this is just for performance testing)

https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.18/index.html?simulation=faraday

@ariel-phet @KatieWoe @loganbraywork can you please report how this impacts the performance on your platform?

**Comment by pixelzoom** [comment]
Performance of 1.0.0-dev.18 is good for me on macOS 10.15.4 + Safari 13.1.

Transforms is probably responsible for the fact that needles are in the wrong place, most noticeable around the magnet:

<img width="529" alt="screenshot_266" src="https://user-images.githubusercontent.com/3046552/79486319-c0575f80-7fd3-11ea-9139-de7caeab72f3.png">

When changing the background color (Projector Mode), images look wrong:

<img width="619" alt="screenshot_265" src="https://user-images.githubusercontent.com/3046552/79486344-ce0ce500-7fd3-11ea-902b-409cb8adc78f.png">

**Comment by KatieWoe** [comment]
Performance on Win 10 Firefox 75.0 is a bit better, but still noticeably laggy. Also seeing the arrow problem @pixelzoom saw above.

**Comment by KatieWoe** [comment]
Performance in IE seems a bit worse honestly.

**Comment by KatieWoe** [comment]
ChromeOS seems a bit better as well. @samreid do want to know any other platforms?

**Comment by KatieWoe** [comment]
I did notice that trying to change the needle size no longer works.
![needlesize](https://user-images.githubusercontent.com/41024075/79497057-50050a00-7fe4-11ea-8426-2b08767d7348.gif)

**Comment by loganbraywork** [comment]
Works great on Windows 10 Chrome, although strange background interaction
![2020-04-16DecafFaradayShapesTest](https://user-images.githubusercontent.com/54685448/79499723-a2e0c080-7fe8-11ea-93f0-8439a7a586cf.PNG)

**Comment by samreid** [comment]
We decided to go with #68, closing.
