### ISSUE TITLE
How should we track Java code changes?

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#66]
I asked in Slack:

> If I make minor changes to the Java simulations for CheerpJ, should I check that in to a monolithic GitHub repo?

@zepumph replied:
> Would the changes be in the source java or in the output js? (edited) 

I said:
> In the source Java

@zepumph said:
> Then why would that not be commited to the svn trunk?

I replied:
> We may need/prefer to keep svn trunk “pristine” for actual Java simulations, translations, etc??? Should I just work in an SVN branch?

@zepumph said:
> I see, neither can live while the other survives sort of thing?
> Yeah a branch in svn seems the best way to handle it
> Is that a pain though?
> Does it mean branching every java sim, or just common code?

I replied:
> Part of it is uncertainty about how existing things work and not wanting to disturb them.

@jonathanolson said:
> SVN branch sounds helpful

I replied:
> Just branching the entire thing, not one per directory.

@jonathanolson said:
> yes

@zepumph said:
> Ahhh, sorry. I forgot how the trunk was setup.
> Sounds good.

I replied: 
> OK I’ll keep that in mind as I proceed.  I’ll probably need a refresher course on SVN and branches.

**Comment by samreid** [comment]
I created a branch called "decaf" and have been making changes there, keeping trunk pristine.

**Comment by kathy-phet** [comment]
@samreid - Can this be closed?
