### ISSUE TITLE
Publish faraday suite 1.0

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#71]
We decided to publish at :

```
https://phet.colorado.edu/sims/cheerpj/[project name]/latest/[project name].html?locale=nn&simulation=flavor
```

Or if we decide to create one file per sim/locale:
```
https://phet.colorado.edu/sims/cheerpj/[project name]/latest/[sim name_LOCALE].html
```

I'm waiting to hear if https://github.com/phetsims/decaf/issues/68 is good enough (we noticed it cuts things off on iPhone landscape), and to see if anything else comes from RC testing.

**Comment by samreid** [comment]
In #68 @kathy-phet said:

> If it works on the iPad - let's publish. We can tweak later if we figure something out.

@KatieWoe reported that it loaded the screen size properly on her test iPad.

**Comment by samreid** [comment]
It looks like the directory is something like /data/web/static/phetsims/sims

**Comment by samreid** [comment]
I tried logging in and creating a directory, but I think it created with the wrong group.  I'll delete it and wait for help from @mattpen .

**Comment by samreid** [comment]
@mattpen and I published this in https://phet.colorado.edu/sims/cheerpj/faraday/latest/faraday.html?simulation=faraday and I'll commit revised publication instructions shortly.

**Comment by mattpen** [comment]
Removing assignment, happy to help further if needed.

**Comment by samreid** [comment]
Publication complete and this was shared on twitter, closing.
