### ISSUE TITLE
Version number in the simulation is stale

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#72]
During #71 I noticed that the version in the title bar doesn't match the decaf version number:

![image](https://user-images.githubusercontent.com/679486/79627705-aadb5600-80f7-11ea-8387-d936f9d60b0a.png)

We may wish to improve this.

Assigned to @kathy-phet for prioritization.

**Comment by kathy-phet** [comment]
This is just a stop gap solution so I am ok with this discrepancy. The version does represent the java version number.

Kathy

Sent from my iPhone

On Apr 17, 2020, at 10:07 PM, Sam Reid <notifications@github.com> wrote:

﻿

During #71<https://github.com/phetsims/decaf/issues/71> I noticed that the version in the title bar doesn't match the decaf version number:

[image]<https://user-images.githubusercontent.com/679486/79627705-aadb5600-80f7-11ea-8387-d936f9d60b0a.png>

We may wish to improve this.

Assigned to @kathy-phet<https://github.com/kathy-phet> for prioritization.

**Comment by kathy-phet** [comment]
@samreid - I'm closing this issue, but reopen if needed.
