### ISSUE TITLE
Streamline the deployment process

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#76]
In slack, I reported:

> I expect it will take around 15 minutes to publish per project.  I’m happy to do this step if you wish, or let me know if you want me to set someone else up to be able to do this process.  Or we could spend half a day making it more automated.

@kathy-phet replied:

> Sam - I think investing a half day making deployment more automated sounds good. I suspect we probably will deploy more than once and if a half day is 4 hours that is only 16 projects and I think we have more than 16 projects to deploy. So saves time even with one deploy. Can you work on that?

**Comment by kathy-phet** [comment]
Sam - let's have you be the point person on the build and deploy for this for now. Thanks.

**Comment by samreid** [comment]
The process seems to be working acceptably well at the moment.  We will have an opportunity to test the "promote dev version to production" version part after more testing completes.  Closing.
