### ISSUE TITLE
Minus sign for partial water charge boxed out English

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/decaf#95]
For https://github.com/phetsims/QA/issues/499. Sugar and Salt Solutions https://phet-dev.colorado.edu/decaf/sugar-and-salt-solutions/1.0.0-dev.4/sugar-and-salt-solutions.html?simulation=sugar-and-salt-solutions. Found on Win 10 Chrome.
On the third screen (water) you can look at the partial charges of the water molecules. The negative sign on the oxygen is a block, which we have previously seen in translations without the proper text. However, this is happening in the English version.
![minusnotthere](https://user-images.githubusercontent.com/41024075/80253564-c504bf00-8636-11ea-9a36-b630e3eaaa1f.png)
It should look like this (java):
![shouldbe](https://user-images.githubusercontent.com/41024075/80253761-12812c00-8637-11ea-845b-96184d0a2d4a.png)

**Comment by lmulhall-phet** [comment]
Possibly https://github.com/phetsims/decaf/issues/91.

**Comment by samreid** [comment]
If I replace it with the letter "d", it looks like this:

![image](https://user-images.githubusercontent.com/679486/81852392-2f16d280-9518-11ea-85ff-68c5337e6549.png)

@kathy-phet @arouinfar does this seem OK with you or what do you recommend?

**Comment by kathy-phet** [comment]
I would probably use just + and -, without any additional letter. 
@emily-phet - What do you think?

**Comment by kathy-phet** [comment]
But Sam, I am confused, because the box is on the negative sign, not on the delta. So why can't you use the delta?

**Comment by samreid** [comment]
Wow, great point!  I'll try that.  Thanks.

**Comment by samreid** [comment]
Looks much better, thanks!

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/679486/81853131-4b673f00-9519-11ea-9183-a281001abfc6.png">

**Comment by samreid** [comment]
Published here: https://phet.colorado.edu/sims/cheerpj/sugar-and-salt-solutions/latest/sugar-and-salt-solutions.html

I set up a development environment on a different machine for this deploy, @KatieWoe can you please spend a few minutes testing this on 1-2 platforms as a sanity test?  If it checks out, you can give @oliver-phet the go-ahead to add it to the published list.

**Comment by KatieWoe** [comment]
Performance is slow, but otherwise looks good on Win 10 Chrome, Firefox, and iPad Safari

**Comment by oliver-phet** [comment]
Published!

**Comment by oliver-phet** [comment]
No one else is assigned, can this be closed?

**Comment by samreid** [comment]
Thanks @oliver-phet and @KatieWoe, closing.
