### ISSUE TITLE
Gene Machine DNA inside toolbox

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/decaf#98]
For https://github.com/phetsims/QA/issues/499. https://phet-dev.colorado.edu/decaf/gene-network/1.0.0-dev.4/gene-network.html?simulation=gene-machine-lac-operon found in ChromeOS at default size.
For certain window sizes, the dna strand can end up inside the toolbox. On chromeOS it is just on the edge, making it difficult, but not yet impossible, to use the sim.
![dnaintoolbox](https://user-images.githubusercontent.com/41024075/80418849-48bbe700-8895-11ea-9076-fae8fc38f56d.png)

**Comment by KatieWoe** [comment]
Bits of Moving Man sliders can be lost in the same way https://phet-dev.colorado.edu/decaf/moving-man/1.0.0-dev.12/moving-man.html?simulation=moving-man

**Comment by lmulhall-phet** [comment]
Messing around with the screen size in Chrome devtools leads to some undesirable behavior as well:

![issue](https://user-images.githubusercontent.com/31285590/80642605-f78e2d80-8a23-11ea-9abf-c8781b919953.png)

**Comment by samreid** [comment]
We decided to apply the minimum size strategy from #96

**Comment by samreid** [comment]
Proposed fix published in dev.5 (on dev and production). @KatieWoe does this fix the problem?

**Comment by KatieWoe** [comment]
Looks like (Small Win 10 Chrome window)

**Comment by samreid** [comment]
Thanks!  Closing.
