### ISSUE TITLE
K and F not visible English Greenhouse Sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/decaf#99]
For https://github.com/phetsims/QA/issues/499. https://phet-dev.colorado.edu/decaf/greenhouse/1.0.0-dev.5/greenhouse.html?simulation=greenhouse
The K and F labels on the thermometers are replaced by boxes in the English Version.
![KandF](https://user-images.githubusercontent.com/41024075/80420439-01832580-8898-11ea-954e-75fe2ca1ea5b.png)

**Comment by loganbraywork** [comment]
Same issue appears in glaciers

**Comment by lmulhall-phet** [comment]
I believe this is an instance of https://github.com/phetsims/decaf/issues/91.

**Comment by samreid** [comment]
Glaciers published here https://phet.colorado.edu/sims/cheerpj/glaciers/latest/glaciers.html

Greenhouse published here: https://phet.colorado.edu/sims/cheerpj/greenhouse/latest/greenhouse.html

@oliver-phet can you please add them to the list?

**Comment by oliver-phet** [comment]
Added.
